INSERT INTO CardModel (id,name,image,description,effect)
VALUES
  (1,"Kylie","https://twitter.com/user/110","Fusce fermentum fermentum","adipiscing elit. Curabitur sed tortor."),
  (2,"Mohammad","http://wikipedia.org/sub/cars","a ultricies adipiscing, enim mi tempor lorem, eget mollis","commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque"),
  (3,"Kristen","http://youtube.com/en-ca","ullamcorper.","scelerisque neque. Nullam nisl. Maecenas malesuada fringilla"),
  (4,"Chadwick","https://zoom.us/group/9","lacus, varius et, euismod et, commodo at,","non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra"),
  (5,"Cruz","http://reddit.com/fr","ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu","placerat, orci lacus"),
  (6,"Driscoll","http://youtube.com/en-us","nec luctus felis purus ac tellus. Suspendisse sed","sem magna nec quam. Curabitur"),
  (7,"Germaine","https://pinterest.com/site","metus urna convallis erat,","semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis"),
  (8,"Imani","http://bbc.co.uk/fr","lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula","vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum"),
  (9,"Ivana","http://walmart.com/en-ca","purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean","ut ipsum ac mi eleifend egestas. Sed pharetra,"),
  (10,"Curran","http://baidu.com/sub/cars","id, libero. Donec consectetuer mauris id sapien. Cras","magna. Ut tincidunt orci quis lectus."),
  (11,"Harper","https://netflix.com/one","Vivamus sit amet risus. Donec egestas. Aliquam nec","mattis velit"),
  (12,"Hannah","https://nytimes.com/group/9","Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit,","lobortis, nisi nibh lacinia"),
  (13,"Emerson","http://nytimes.com/user/110","viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec","vitae aliquam eros turpis non enim."),
  (14,"Dawn","http://cnn.com/en-us","elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique","rhoncus. Nullam velit dui,"),
  (15,"Maxine","https://nytimes.com/en-ca","sit amet lorem semper auctor. Mauris","non ante bibendum ullamcorper. Duis cursus, diam at"),
  (16,"Magee","https://reddit.com/group/9","dictum eu, eleifend nec, malesuada ut, sem.","condimentum. Donec at arcu. Vestibulum ante ipsum"),
  (17,"Nora","http://twitter.com/site","Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam.","mi lorem, vehicula et, rutrum eu, ultrices sit"),
  (18,"Lane","https://walmart.com/en-ca","euismod est arcu ac orci. Ut semper pretium","amet lorem"),
  (19,"Jack","http://wikipedia.org/one","montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean","ornare. In faucibus. Morbi vehicula. Pellentesque"),
  (20,"Sage","https://netflix.com/sub","tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum","augue malesuada"),
  (21,"Ocean","https://reddit.com/settings","et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim","eleifend, nunc risus varius"),
  (22,"Shoshana","http://pinterest.com/fr","egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a,","iaculis nec, eleifend non, dapibus rutrum,"),
  (23,"Sonia","https://google.com/sub","Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla.","litora torquent per"),
  (24,"Kenyon","http://facebook.com/en-us","ullamcorper. Duis cursus, diam","libero et tristique pellentesque, tellus"),
  (25,"Grant","http://naver.com/settings","at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed","enim consequat purus."),
  (26,"Noble","http://yahoo.com/sub","non, lacinia at, iaculis quis, pede. Praesent","molestie orci"),
  (27,"Amelia","http://netflix.com/en-us","amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse","ipsum dolor sit amet,"),
  (28,"Ciara","https://whatsapp.com/user/110","aliquet molestie tellus. Aenean egestas","Nulla semper tellus id nunc interdum feugiat. Sed nec metus"),
  (29,"Joseph","http://naver.com/fr","consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat","tellus faucibus"),
  (30,"Shelly","http://netflix.com/settings","eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.","Donec est. Nunc ullamcorper, velit in aliquet lobortis,");
